### ISSUE TITLE
Top padding for tabs in One Dark's compact mode is too small

### ISSUE THREAD

**Issue by gee-forr** [lexicalunit/no-title-bar#10]
Hi there,

Thanks for this plugin, it's so useful, especially when devving on a laptop, those extra pixel make a difference :)

I've noticed a bug where the top padding seems a little off. Is this a bug? It looks different to the screenshots you've posted but I'm not 100% sure.

I've attached a screenshot to show you what it looks like on my machine. Let me know if you need more info from me.

Thanks :)
<img width="1085" alt="screen shot 2017-01-12 at 16 08 08" src="https://cloud.githubusercontent.com/assets/345730/21892997/e76765e4-d8e1-11e6-894b-ac09e4e2a0f3.png">

**Comment by lexicalunit** [comment]
Hi, thanks for reporting the issue! You're right, the screenshot you posted does look a bit weird.

I'm using the [`native-ui`](https://atom.io/themes/native-ui) theme in my screenshots. I assume you're using the One Dark theme? I'll see if I can find a solution that works for both.

**Comment by gee-forr** [comment]
Hi @lexicalunit...

Yeah - I'm using One Dark. I've just tried with Native-UI, and it works perfectly. Unfortunately, I've tried with every other theme I had on hand; Nucleus, Isotope, and Material, and they have the same issue as One Dark.

**Comment by lexicalunit** [comment]
Ah, I think I know why this is happening with One Dark. It's due to the Compact Mode setting:

Normal One Dark:

<img width="861" alt="normal" src="https://cloud.githubusercontent.com/assets/1903876/21956498/0cb7725a-da48-11e6-83fa-a6afa2ed1a16.png">

Compact One Dark:

<img width="790" alt="compact" src="https://cloud.githubusercontent.com/assets/1903876/21956501/20da0ba8-da48-11e6-8bab-9836add9b28c.png">

---

You can make One Dark Compact Mode look a bit better by adding this tweak to your `styles.less`:

```
atom-workspace.theme-one-dark-ui .tab-bar .tab {
  padding-top: 5px !important;
}
```

<img width="816" alt="screen shot 2017-01-14 at 11 04 19 am" src="https://cloud.githubusercontent.com/assets/1903876/21956540/3e9bd436-da49-11e6-9ccc-09f0f974501c.png">

However I can't figure out how to enable this _only when Compact Mode is enabled_. We wouldn't want to have this enabled when a user is using normal mode. Sadly, I don't think there's a way to match the following using CSS, which is what we'd need to do to handle this properly.

```
<html theme-one-dark-ui-layoutmode="compact" theme-one-dark-ui-tabsizing="auto">
```

However, if you're happy adding the above snippet to your `styles.less` it should solve your issue and we can close this ticket for now 👍

**Comment by gee-forr** [comment]
Hi,

That's perfect! Thank you so much :)
