### ISSUE TITLE
Tab drag cursor when Tree View collapsed

### ISSUE THREAD

**Issue by AlecRust** [lexicalunit/no-title-bar#22]
If Atom's Tree View is collapsed, dragging a tab to the left shows the blue cursor in the corner of the window, rather than to the left of the first tab:

![screencast](http://i.imgur.com/H039Pmx.gif)

Is this expected behaviour?

**Comment by lexicalunit** [comment]
Definitely an unintended side effect!

**Comment by lexicalunit** [comment]
So it turns out this is actually caused by the same issue which is at fault in #19. I've [opened a thread on discuss.atom.io](https://discuss.atom.io/t/help-with-css-to-select-element-when-another-is-hidden/44352) to ask for help in resolving this because I'm very much at a loss here. It may require some JavaScript hacking to resolve, which would suck. A pure CSS solution is ideal but I don't know if it's possible anymore with the way Atom has implemented Docks.

**Comment by lexicalunit** [comment]
@AlecRust please give version 1.1.0 a try and see if it fixes this issue for you!

**Comment by AlecRust** [comment]
Hmm looks like I can't update to that with my Atom version (1.18.0).

![screenshot](https://i.imgur.com/AmXAF0R.png)

**Comment by lexicalunit** [comment]
Oh sorry, the latest version of `no-title-bar` requires at least Atom 1.19.0 which is only in beta at the moment. It should be released soon though :)

**Comment by AlecRust** [comment]
Can confirm this works on 1.19.0 :)
