### ISSUE TITLE
Interferes with move-status-items

### ISSUE THREAD

**Issue by danielbayley** [lexicalunit/no-title-bar#26]
I use the [_move-status-items_](https://atom.io/packages/move-status-items) package to reorder items in the status bar, but this package makes _any_ drag event anywhere on status bar move the entire window, resulting in these 2 packages being mutually exclusive!

Looking at some of the other issues related to this… I think making the whole app draggable then disabling certain areas was maybe a bit extreme?

**Comment by lexicalunit** [comment]
It's much easier to enumerate the places we don't want to drag the window than to enumerate all the places we do want to drag the window. At least... for me. Because I want to be able to drag the window from just about anywhere, with only some exceptions. So naturally that is how I implemented this package.

However it's becoming clear to me that that is a preference. And there are many people who would like to see a more conservative option. You're right, @danielbayley, "enable dragging _here_, and only _here_, and nowhere else" seems to be a common request.

🤔 

I'll have to see if I can add a configuration setting to toggle between conservative and aggressive modes (btw I'm open to suggestions for better names for those).

In the mean time you can add this to your `styles.less` to workaround the status bar issue:

```less
.no-title-bar:not(.fullscreen) > atom-workspace {
  .status-bar {
    -webkit-app-region: no-drag;
  }
}
```

**Comment by danielbayley** [comment]
Well the only reason it's a problem is because it gets in the way of other UI elements… I had to also add `atom-dock` to that `styles` override because it was interfering with that too, and who knows what else in future… it seems to me that approach doesn't scale.

**Comment by lexicalunit** [comment]
If I had done it the other way around I'd probably be getting lots of "why can't I drag the window from _here_?" issues 😉

**Comment by danielbayley** [comment]
Probably 🙂 But I think that list would be a lot shorter, considering you can't possibly take into account every potential UI element of every future package… Atom is only going to grow!

**Comment by lexicalunit** [comment]
@danielbayley you'll probably want to disable `enableLiberalWindowDragging` in release v1.5.0 😃
