### ISSUE TITLE
This packages makes it impossible to resize the sidebar 

### ISSUE THREAD

**Issue by agustif** [lexicalunit/no-title-bar#30]
So this is useful but the sidebar is impossible to resize with extra packages

**Comment by lexicalunit** [comment]
This is probably happening because of the code that enables window dragging in empty space. Version 1.7.1 for Atom versions 1.20+ should resolve this particular issue, however that means it's currently only available to users of Atom Beta. If you're not using Atom Beta, you have two options:

1. **Disable** the "Enable Liberal Window Dragging" setting in the package. This may resolve your issue. You will continue to be able to drag the window using empty space in the tab bar, but no where else.
2. If #1 doesn't work or you don't want to disable that setting, you need to [make this change](https://github.com/lexicalunit/no-title-bar/commit/6973298478750f3b7bd0018149b2504b70d149ae) to resolve the issue. Navigate to your `.atom` directory &mdash; See [these Atom docs](http://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode) and use the `MAC`,  `WINDOWS`,  or `LINUX` links at the top of that page to help determine where your `.atom` directory is located on your machine &mdash; and edit the file `.atom/packages/no-title-bar/styles/no-title-bar.less` to remove the entire line containing `.tree-view` (line 67 for v1.5.0 of this package) _and the trailing comma from the line above it_. Save the file and restart Atom.

**Comment by lexicalunit** [comment]
Now that Atom 1.20 has been released, this issue should be resolved. 🎉
