### ISSUE TITLE
1.6.0 is the "latest compatible version"

### ISSUE THREAD

**Issue by everdimension** [lexicalunit/no-title-bar#32]
I'm currently running the latest atom version (`v1.19.7`) and I see this warning:

![image](https://user-images.githubusercontent.com/5347023/30215571-0bda37ce-94b9-11e7-80db-f4ea040c1d4c.png)

*Version 1.6.0 is not the latest version available for this package, but it's the latest that is compatible with your version of Atom.*

Seems something's wrong?

**Comment by lexicalunit** [comment]
The latest version of Atom is **1.20.0-beta5** and the latest version of `no-title-bar` takes advantage of new capabilities of this version of Atom. For Atom versions 1.19.x, the latest version of `no-title-bar` available is 1.5.0. Version 1.6.0 is the first version of this package to require Atom version at least 1.20.0. If you have 1.6.0 installed somehow, you should uninstall the package and try re-installing so that you get the correct version.

**Comment by everdimension** [comment]
Okay, thanks.
I wish atom somehow indicated that your latest stable version relies on atom beta, but that's obviously not something you control.
