### ISSUE TITLE
Unable to move window with tree view scrolled down

### ISSUE THREAD

**Issue by pushchris** [lexicalunit/no-title-bar#33]
Currently am unable to utilize the space next to the traffic lights to move the window when the tree view is scrolled more than 30 or so pixels from the top, or when tabs have scrolled more than the width of the tree view over. It could be that somehow that space is getting covered by another layer? I've attached a gif of it below:

![ezgif-4-67170ba34b](https://user-images.githubusercontent.com/679974/30514969-5e2b5332-9ae5-11e7-9586-75b8a787476c.gif)

Using Atom 1.20 & no-title-bar 1.10.0 with One Dark theme installed and no custom styling

**Comment by lexicalunit** [comment]
Just got back from Vacation! Excellent bug report and screencast demonstrating the problem, thanks for that <3 I'll try to look into this and fix it as soon as I can get caught back up with everything.

**Comment by lexicalunit** [comment]
I think this is maybe similar to the issue https://github.com/electron/electron/issues/3647 somehow... maybe? I couldn't figure out a workaround using JS/LESS in any case 😢 

One easy workaround that works on all macOS windows is "if you hover the mouse over the top edge of the window until you see a resize cursor and then hold and drag to the side instead of up and down to resize it will let you move the window" -- via [this comment](https://github.com/electron/electron/issues/3647#issuecomment-291386544).

I've subscribed to that issue so that whenever it gets resolved I'll can remember to revisit this issue.

**Comment by pushchris** [comment]
@lexicalunit many thanks for looking into it! The workaround you described does seem to work and I can make due with that. Hopefully they resolve it in the future!

**Comment by lexicalunit** [comment]
I think I may have actually found a way to workaround this issue! I'm a little wary though because it feels somewhat hacky. Regardless, released in v1.11.0. If it causes more issues than it's worth I can always just remove it in a later version. Don't hesitate to report any further issues :)

**Comment by pushchris** [comment]
Almost perfect, it now works no matter where you are scrolled on the tree view, but it still stops working if you have scrolled over more than a couple of tabs. That being said, a big improvement overall, thank you!

**Comment by lexicalunit** [comment]
Fixed in v1.11.2 🤞

**Comment by pushchris** [comment]
@lexicalunit 🙏🏻🙏🏻🙏🏻 you are the best! Works like a charm now
